#!/usr/bin/env bash
# Fetch latest changes
git fetch --prune

# Reset current branch to the remote branch
git reset --hard @{upstream}

# Trash untracked files
(git ls-files --others --exclude-standard -z | xargs -0 trash) && echo "Trashed untracked files"
